module.exports = {
    list: [
        {id: 100, val:"Continue"},
        {id: 101, val:"Switching protocols"},
        {id: 102, val:"Processing"},
        {id: 103, val:"Early Hits"},     
        {id: 200, val:"OK"},
        {id: 201, val:"Created"},
        {id: 202, val:"Accepted"},
        {id: 203, val:"Non-Authoritative Information"},
        {id: 204, val:"No Content"},
        {id: 205, val: "Reset Content"},
        {id: 206, val: "Partial Content"},
        {id: 207, val: "Multi-Status"},
        {id: 208, val: "Already Reported"},
        {id: 226, val: "IM Used"},
        {id: 300, val: "Multiple Choices"},
        {id: 301, val: "Moved Permanently"},
        {id: 302, val: `Found (Previously "Moved Temporarily")`},
        {id: 303, val: "See Other"},
        {id: 304, val: "Not Modified"},
        {id: 305, val: "Use Proxy"},
        {id: 306, val: "Switch Proxy"},
        {id: 307, val: "Temporary Redirect"},
        {id: 308, val: "Permanent Redirect"},
        {id: 400, val: "Bad Request"},
        {id: 401, val: "Unauthorized"},
        {id: 402, val: "Payment Required"},
        {id: 403, val: "Forbidden"},
        {id: 404, val: "Not Found"},
        {id: 405, val: "Method Not Allowed"},
        {id: 406, val: "Not Acceptable"},
        {id: 407, val: "Proxy Authentication Required"},
        {id: 408, val: "Request Timeout"},
        {id: 409, val: "Conflict"},
        {id: 410, val: "Gone"},
        {id: 411, val: "Length Required"},
        {id: 412, val: "Precondition Failed"},
        {id: 413, val: "Payload Too Large"},
        {id: 414, val: "URI Too Long"},
        {id: 415, val: "Unsupported Media Type"},
        {id: 416, val: "Range Not Satisfiable"},
        {id: 417, val: "Expectation Failed"},
        {id: 418, val: "I'm a Teapot"},
        {id: 421, val: "Misdirected Request"},
        {id: 422, val: "Unprocessable Entity"},
        {id: 423, val: "Locked"},
        {id: 424, val: "Failed Dependency"},
        {id: 425, val: "Too Early"},
        {id: 426, val: "Upgrade Required"},
        {id: 428, val: "Precondition Required"},
        {id: 429, val: "Too Many Requests"},
        {id: 431, val: "Request Header Fields Too Large"},
        {id: 451, val: "Unavailable For Legal Reasons"},
        {id: 500, val: "Internal Server Error"},
        {id: 501, val: "Not Implemented"},
        {id: 502, val: "Bad Gateway"},
        {id: 503, val: "Service Unavailable"},
        {id: 504, val: "Gateway Timeout"},
        {id: 505, val: "HTTP Version Not Supported"},
        {id: 506, val: "Variant Also Negotiates"},
        {id: 507, val: "Insufficient Storage"},
        {id: 508, val: "Loop Detected"},
        {id: 510, val: "Not Extended"},
        {id: 511, val: "Network Authentication Required"}
    ]
}